title: JABBADAFUNK
meta_tags: funk, rock, rap
meta_desc: funkrock mit rap

facebook: https://fb.com/jabbadafunk
spotify: https://open.spotify.com/album/4yVEkiFWnm4SmryiqMp31E?si=XpE94xX2SpKtJJuijMPzkg
youtube: https://www.youtube.com/watch?v=U5o3eRyp4qw
instagram: https://www.instagram.com/jabbadafunk/


exclude: [ "README.md" ]
