title: JABBADAFUNK
meta_tags: funk, rock, rap
meta_desc: funkrock mit rap

facebook: https://fb.com/jabbadafunk
soundcloud: https://soundcloud.com/user-763933125
youtube: https://www.youtube.com/watch?v=Qc6cF5pMobo
instagram: https://www.instagram.com/jabbadafunk/


exclude: [ "README.md" ]
